version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./html:/var/www/html
    environment:
      DEBIAN_FRONTEND: noninteractive
    command: ["apache2ctl", "-D", "FOREGROUND"]
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: elgg_db
      MYSQL_USER: elgg_user
      MYSQL_PASSWORD: elgg_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: