name: Build and Run Elgg

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose build

      - name: Run Elgg container
        run: docker-compose up -d

      - name: Wait for Elgg to start
        run: |
          n=0
          max_attempts=5
          retry_interval=10
          
          until [ $n -ge $max_attempts ]
          do
            status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
            if [ "$status_code" -eq 200 ]; then
              echo "Elgg is running successfully."
              exit 0
            else
              echo "Failed to access Elgg. Status code: $status_code. Retrying in $retry_interval seconds..."
              if [ $n -eq $((max_attempts - 1)) ]; then
                curl_output=$(curl -s http://localhost)
                echo "Curl output on final attempt: $curl_output"
              fi
              n=$((n+1))
              sleep $retry_interval
            fi
          done
          
          echo "Failed to confirm Elgg is running after $max_attempts attempts."
          exit 1
          
      - name:  Periksa Log
        run: man curl | grep "exit code 56"

    #   - name: Check Elgg availability
    #     run: |
    #       status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
    #       if [ $status_code -eq 200 ]; then
    #         echo "Elgg is running successfully."
    #       else
    #         echo "Failed to access Elgg. Status code: $status_code"
    #         exit 1
    #       fi

      # Add additional steps for functional testing if needed
      # - name: Run Elgg functional tests
      #   run: |
      #     # Your functional tests commands here
