name: Build and Run Elgg

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose build

      - name: Run Elgg container
        run: docker-compose up -d

      - name: Get AUT URL
        run: |
          URL=$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
          echo "URL=$URL" >> $GITHUB_ENV

      - name: Checking service availability
        run: |
          max_attempts=5
          retry_interval=10
          # Menggunakan port 80 sesuai contoh Docker Compose dan alamat IP host yang telah didapatkan
          service_url=http://$URL:80
          
          for ((attempt=1; attempt<=max_attempts; attempt++)); do
            echo "Checking service availability (Attempt $attempt of $max_attempts)..."
            # Menyimpan response body ke file untuk debugging
            curl_output=$(curl -s -w "%{http_code}" -o response.txt "$service_url")
            # Membaca status code dari output
            status_code=$(tail -n1 response.txt)
            echo "Response Body:"
            cat response.txt
            echo "Status Code: $status_code"
            
            if [[ "$status_code" -eq 200 ]]; then
              echo "Service is available."
              exit 0
            else
              echo "Service is not available yet. Status code: $status_code."
              if [[ $attempt -lt $max_attempts ]]; then
                echo "Waiting $retry_interval seconds before retrying..."
                sleep $retry_interval
              else
                echo "Max attempts reached. Unable to confirm service availability."
                exit 1
              fi
            fi
          done
